# go mod using go 1.25
FROM golang:1.25-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
# set GOPROXY to speed up module download
RUN go env -w GOPROXY=https://goproxy.cn,direct
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o agrisense ./cmd/agrisense

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /app/agrisense .
CMD ["./agrisense"]
